<?php

namespace ContainerAxszfUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nw7ZQRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nw7ZQ_r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nw7ZQ_r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'X' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'mg' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'X' => 'App\\Repository\\GenreRepository',
            'mg' => '?',
        ]);
    }
}
