<?php

namespace ContainerAxszfUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kgu6boBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kgu6boB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kgu6boB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\GenreController::addgenre' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\GenreController::liste' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\GenreController::remove' => ['privates', '.service_locator.nw7ZQ_r', 'get_ServiceLocator_Nw7ZQRService', true],
            'App\\Controller\\GenreController::updateGenre' => ['privates', '.service_locator.tjgKsjJ', 'get_ServiceLocator_TjgKsjJService', true],
            'App\\Controller\\ReclamationController::addrec' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::liste1' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\ReclamationController::liste2' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\ReclamationController::pdf' => ['privates', '.service_locator.uhlUN92', 'get_ServiceLocator_UhlUN92Service', true],
            'App\\Controller\\ReclamationController::remove' => ['privates', '.service_locator.4P9LgdQ', 'get_ServiceLocator_4P9LgdQService', true],
            'App\\Controller\\ReclamationController::removefront' => ['privates', '.service_locator.4P9LgdQ', 'get_ServiceLocator_4P9LgdQService', true],
            'App\\Controller\\ReclamationController::updateType' => ['privates', '.service_locator.82pMBjW', 'get_ServiceLocator_82pMBjWService', true],
            'App\\Controller\\ReclamationController::updateTypeback' => ['privates', '.service_locator.82pMBjW', 'get_ServiceLocator_82pMBjWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\GenreController:addgenre' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\GenreController:liste' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\GenreController:remove' => ['privates', '.service_locator.nw7ZQ_r', 'get_ServiceLocator_Nw7ZQRService', true],
            'App\\Controller\\GenreController:updateGenre' => ['privates', '.service_locator.tjgKsjJ', 'get_ServiceLocator_TjgKsjJService', true],
            'App\\Controller\\ReclamationController:addrec' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:liste1' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\ReclamationController:liste2' => ['privates', '.service_locator.MKx7VzI', 'get_ServiceLocator_MKx7VzIService', true],
            'App\\Controller\\ReclamationController:pdf' => ['privates', '.service_locator.uhlUN92', 'get_ServiceLocator_UhlUN92Service', true],
            'App\\Controller\\ReclamationController:remove' => ['privates', '.service_locator.4P9LgdQ', 'get_ServiceLocator_4P9LgdQService', true],
            'App\\Controller\\ReclamationController:removefront' => ['privates', '.service_locator.4P9LgdQ', 'get_ServiceLocator_4P9LgdQService', true],
            'App\\Controller\\ReclamationController:updateType' => ['privates', '.service_locator.82pMBjW', 'get_ServiceLocator_82pMBjWService', true],
            'App\\Controller\\ReclamationController:updateTypeback' => ['privates', '.service_locator.82pMBjW', 'get_ServiceLocator_82pMBjWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\GenreController::addgenre' => '?',
            'App\\Controller\\GenreController::liste' => '?',
            'App\\Controller\\GenreController::remove' => '?',
            'App\\Controller\\GenreController::updateGenre' => '?',
            'App\\Controller\\ReclamationController::addrec' => '?',
            'App\\Controller\\ReclamationController::liste1' => '?',
            'App\\Controller\\ReclamationController::liste2' => '?',
            'App\\Controller\\ReclamationController::pdf' => '?',
            'App\\Controller\\ReclamationController::remove' => '?',
            'App\\Controller\\ReclamationController::removefront' => '?',
            'App\\Controller\\ReclamationController::updateType' => '?',
            'App\\Controller\\ReclamationController::updateTypeback' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\GenreController:addgenre' => '?',
            'App\\Controller\\GenreController:liste' => '?',
            'App\\Controller\\GenreController:remove' => '?',
            'App\\Controller\\GenreController:updateGenre' => '?',
            'App\\Controller\\ReclamationController:addrec' => '?',
            'App\\Controller\\ReclamationController:liste1' => '?',
            'App\\Controller\\ReclamationController:liste2' => '?',
            'App\\Controller\\ReclamationController:pdf' => '?',
            'App\\Controller\\ReclamationController:remove' => '?',
            'App\\Controller\\ReclamationController:removefront' => '?',
            'App\\Controller\\ReclamationController:updateType' => '?',
            'App\\Controller\\ReclamationController:updateTypeback' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
