<?php

namespace ContainerAxszfUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4P9LgdQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4P9LgdQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4P9LgdQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'X' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'mg' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'X' => 'App\\Repository\\ReclamationRepository',
            'mg' => '?',
        ]);
    }
}
