<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxszfUM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxszfUM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxszfUM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxszfUM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxszfUM\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxszfUM',
    'container.build_id' => '5cc5a0ec',
    'container.build_time' => 1734555190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxszfUM');
